### ISSUE TITLE
Certificate is invalid for docker with v0.11.1 KIND

### ISSUE THREAD

**Issue by yidongw** [kind-ci/examples#35]
I was using the https://github.com/kind-ci/examples/blob/master/.gitlab-ci.yml, but with different versions.

```
    KUBECTL: v1.23.0
    KIND: v0.11.1
```
still works fine.

Starting from `KIND: v0.12.0`, Gitlab CI will give me the following error
```
$ kubectl get nodes -o wide
Unable to connect to the server: x509: certificate is valid for 582660598-control-plane, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, localhost, not docker
```

How can I fix it?

**Comment by frotsch** [comment]
I have the same issue with v0.14.0 although I include the kubeadmConfigPatchesJSON6902 thing

```
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  apiServerAddress: "0.0.0.0"

# add to the apiServer certSANs the name of the docker (dind) service in order to be able to reach the cluster through it
kubeadmConfigPatchesJSON6902:
  - group: kubeadm.k8s.io
    version: v1beta2
    kind: ClusterConfiguration
    patch: |
      - op: add
        path: /apiServer/certSANs/-
        value: docker
nodes:
  - role: control-plane
  - role: worker
  - role: worker
```
